# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation date')),
                ('complete', models.BooleanField(default=False, verbose_name='Is complete')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Pricipal'), (1, 'Beverage'), (2, 'Dessert')], verbose_name='Category')),
                ('unitary', models.BooleanField(default=True, verbose_name='Is unitary')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
