# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:25
from __future__ import unicode_literals

from django.db import migrations


products = [
    {
        'name': 'Ensalada de espinacas',
        'price': 1.65,
        'category': 0,
        'unitary': False,
    }, {
        'name': 'Tortellini alla carbonara',
        'price': 1.30,
        'category': 0,
        'unitary': False,
    }, {
        'name': 'Pollo al curry',
        'price': 1.55,
        'category': 0,
        'unitary': False,
    }, {
        'name': 'Arroz con verduras',
        'price': 1.55,
        'category': 0,
        'unitary': False,
    }, {
        'name': 'Pizza primavera',
        'price': 2,
        'category': 0,
        'unitary': True,
    }, {
        'name': 'Carne estofada',
        'price': 2.15,
        'category': 0,
        'unitary': False,
    }, {
        'name': 'Agua',
        'price': 1.20,
        'category': 2,
        'unitary': True,
    }, {
        'name': 'Zumo de naranja',
        'price': 2,
        'category': 2,
        'unitary': True,
    }, {
        'name': 'Manzana',
        'price': 2,
        'category': 3,
        'unitary': True,
    }, {
        'name': 'Tarta de queso',
        'price': 2.5,
        'category': 3,
        'unitary': True,
    },
]


def initial_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    for product in products:
        Product(
            name=product['name'],
            price=product['price'],
            category=product['category'],
            unitary=product['unitary'],
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_products)
    ]
